### ISSUE TITLE
CSS Syntax Error

### ISSUE THREAD

**Issue by silaspath** [JustGoodUI/dante-astro-theme#1] opened 2024-01-19 06:45 UTC
Hey thanks for writing this

I found a problem after clean install:
```The max-w-64 class does not exist. If max-w-64 is a custom class, make sure it is defined within a @layer directive.
```

Component: components/Nav.astro:44:13

I see this when I go to the home page

**Comment by astab** [comment] 2024-01-19 08:05
Hi @silaspath, thank you for trying out Dante theme. I don't see any issues on my machine. Can you please give me more details about your environment?

**Comment by astab** [comment] 2024-02-14 14:20
I'm closing this issue as I can't reproduce it.

**Closed by astab** 2024-02-14 14:20 UTC
